### ISSUE TITLE
Add DEV badge once it lands in FontAwesome

### ISSUE THREAD

**Issue by benhalpern** [aspittel/learn-code-from-us#1]
The [dev.to](/) badge [is about to land in the FontAwesome set](https://github.com/FortAwesome/Font-Awesome/issues/12589#issuecomment-419214462) and I think it should be added as an option here, as many of these folks will have DEV profiles. 🙂

**Comment by aspittel** [comment]
Done! Added a form field so that I have those profiles as soon as the icon comes out on React-Icons

**Comment by aspittel** [comment]
This feature is in production!
