### ISSUE TITLE
Add GitHub Files

### ISSUE THREAD

**Issue by aspittel** [aspittel/learn-code-from-us#13]
- [ ] Code of Conduct
- [ ] Pull Request Template
- [ ] Issue Template
- [x] Contributing Guide

**Comment by aaj013** [comment]
I'd like to work on this!

**Comment by koolamusic** [comment]
- Code of Conduct
- Contributing Guide

Done

**Comment by dolani** [comment]
I came across a roadmap on react from my medium lists. I would like to add to the readme file.

**Comment by dolani** [comment]
I'd like to work in this. I'd like to add more beginner friendly react tutorials.
