### ISSUE TITLE
Add React Tutorials to the ReadMe

### ISSUE THREAD

**Issue by aspittel** [aspittel/learn-code-from-us#26]
I would love for this to be as beginner-friendly as possible, so I wanted to add some React tutorials to the documentation.

Here's the one that I wrote, https://zen-of-programming.com/beginners-guide-react, but I would love other people to add their favorite *free* ones as well!

**Comment by krisgardiner** [comment]
Would love to add some tutorials that have helped me :)

**Comment by aspittel** [comment]
Yes! Would love more @zackhitch and @krisgardiner

**Comment by jeremybbauer** [comment]
I would also like to contribute some resources, if that’s okay. 

I’m a little new to contributing to other people’s repos. Is it okay to open a pull request for this, or should I wait for the open pull request on this issue to be decided on first?

Love the “The Zen of Programming” newsletter, by the way 🙌✨!

**Comment by aspittel** [comment]
Yes for sure @jeremybbauer! Go for it! Thank you so much!

**Comment by taverasmisael** [comment]
I added a React-Router beginner one because I think is important to learn at least the basics of it

**Comment by jeremybbauer** [comment]
I added Glitch's React Starter Kit. Thanks, @aspittel !

**Comment by GaProgMan** [comment]
I wonder whether there should be a separate markdown file for tutorials. Perhaps something like:

# Tutorials

The following tutorials are separated by technology and might be useful for contributors who are new to the technology stacks which this project uses, and would like to learn more before contributing.

### React

#### Beginners/Intro to React

#### More advanced/Specific React Topics

### HTML & CSS

#### Similar Headers Here

### A.N.Other technology

**Comment by afreen23** [comment]
#51

**Comment by aspittel** [comment]
Love that idea @GaProgMan! Let's do it!
