### ISSUE TITLE
Add Linting

### ISSUE THREAD

**Issue by aspittel** [aspittel/learn-code-from-us#28]
I like StandardJS for JavaScript formatting -- would be great to standardize!

**Comment by jeffhoelter** [comment]
I'd suggest adding Prettier too, maybe with https://github.com/sheerun/prettier-standard

**Comment by aroup** [comment]
Yes, I can add that too with eslint. @jeffhoelter @aspittel

**Comment by jimmiehansson** [comment]
@aroup I didn't see your comment, I've fixed it ready for PR, but I'll let you go ahead 💯

**Comment by aspittel** [comment]
Awesome, thank you both!
