### ISSUE TITLE
Add Automated Testing

### ISSUE THREAD

**Issue by aspittel** [aspittel/learn-code-from-us#3]
Add tests for the different components using Jest

**Comment by NeelShah18** [comment]
I can help you with it.

**Comment by aspittel** [comment]
Awesome, thank you so much @NeelShah18!

**Comment by cliff76** [comment]
I'm on it!

**Comment by cliff76** [comment]
Sorry, I started working on this w/o checking the issues responses. I've only added the base requirements for jest/enzyme. Feel free to add to, remove, or totally butcher what I've proposed in my PR.

**Comment by NeelShah18** [comment]
ok good luck @cliff76  :-)

**Comment by VivekNayyar** [comment]
@cliff76 are you working on this. If not then I would like to take this up. Thanks.

**Comment by nobuti** [comment]
I've opened a PR for this issue, I didn't realize there were other working on it, feel free to close it. Sorry!

**Comment by cliff76** [comment]
@vivek12345 yes, I've started in on PR https://github.com/aspittel/learn-code-from-us/pull/37 which was merged yesterday. I'm still game for adding more test cases and such. Feel free to jump in and help out! :)

**Comment by cliff76** [comment]
@nobuti I've rebased your branch onto master. I'll submit as a new PR.

**Comment by cliff76** [comment]
@aspittel Please close @nobuti's PR in favor of this rebased version of it:
https://github.com/aspittel/learn-code-from-us/pull/48

**Comment by nobuti** [comment]
:heart: @cliff76

**Comment by aspittel** [comment]
Cool -- think we've made good progress on this!
