### ISSUE TITLE
Transparent nav bar is a bit funky on desktop

### ISSUE THREAD

**Issue by benhalpern** [aspittel/learn-code-from-us#32]
Just a small design thought: The nav bar as you scroll is transparent and becomes unreadable as you scroll.

![](https://cl.ly/b3202f17c863/Image%202018-10-19%20at%2012.47.00%20PM.png)

As a side comment, it may be a bit too big for a fixed nav. It would cover up a decent amount of the screen as one scrolls. I prefer slightly shorter navs. You could also remove the `fixed` for the whole bar and maybe just leave the true "nav" sticky on the left-most side (similar to like [this](https://theoutline.com/)).

Just some thoughts 🙂

**Comment by aspittel** [comment]
Hey @benhalpern! I think this is the older version of the site -- I wonder if it's still cached from the old version. Totally agree though that it's better without it!

I love the Outline's design, and that nav is genius!

**Comment by benhalpern** [comment]
@aspittel Ah yes you're right!

I guess the issue is clearing the cache appropriately 🤔

I'll close this.
