### ISSUE TITLE
Add script for adding new features

### ISSUE THREAD

**Issue by aspittel** [aspittel/learn-code-from-us#38]
Right now, it takes some manual work to add new people. I'm going to expedite this with a node script.

**Comment by GaProgMan** [comment]
Is the process for adding new people documented anywhere?

**Comment by aspittel** [comment]
Yeah -- right now there's [a form](https://airtable.com/shrYbUMMlR1iVpA1l) that you fill out (that should probably be added to the readme) then I pull the data from the API and clean it up a little for the data.json file. Going to work on expediting that process.

**Comment by aspittel** [comment]
This is fixed with https://github.com/aspittel/learn-code-from-us/pull/57! Documentation has also been added
