### ISSUE TITLE
Continuous Integration + Docker

### ISSUE THREAD

**Issue by nikoheikkila** [aspittel/learn-code-from-us#52]
Hi!

I see you're missing CI checks for this project. I would be interested in adding these especially since there are automated tests in #3 under progress. Basic code linting and test running would probably be enough.

Are you familiar with Travis CI or do you prefer some other service?

Additionally, I could add a Dockerfile to this project so those who have trouble with Node for whatever reason could contribute just as easily. What do you think?

**EDIT:** Tried to create some basic checks with Travis on my fork which passed. See [here](https://travis-ci.com/nikoheikkila/learn-code-from-us) for results. ✌️

**Comment by aspittel** [comment]
Hi @nikoheikkila! Code linting and test running would be great, so would Travis CI. I think Docker may be a lot for this project, but that could be cool too -- anybody else have feedback on whether it would be helpful?
