### ISSUE TITLE
Card images don't always fill available space

### ISSUE THREAD

**Issue by twosmalltrees** [aspittel/learn-code-from-us#69]
### The Issue
👋 Hi there! I've noticed room for a possible improvement for the styles of the Card images. Currently if the provided image is wider than it is tall, the result is white space at the bottom of the image, which looks a little odd. Screenshots below...

<img width="252" alt="screen shot 2018-10-27 at 8 38 22 am" src="https://user-images.githubusercontent.com/15548396/47594128-b1d34d80-d9c5-11e8-9e3a-2267ee35f5b1.png">

### Proposed Solution
A simple solution (PR incoming shortly) would be to use: `object-fit: cover` to enforce that the image should cover the containing div.

<img width="243" alt="screen shot 2018-10-27 at 8 38 35 am" src="https://user-images.githubusercontent.com/15548396/47594127-b1d34d80-d9c5-11e8-8e2c-1b91342942b8.png">

**Comment by twhite96** [comment]
Hmmmm. Is it all versions of IE?

**Comment by twhite96** [comment]
I'm currently playing with transitions on hover. I'll take a look at this and try to find a compatible solution.

**Comment by twosmalltrees** [comment]
Hi @twhite96, unfortunately yeah looks like it's unsupported on all versions of IE. Supported from Edge 16 onwards I believe

**Comment by twhite96** [comment]
@aspitell is it important to keep IE support at this time? If so, we should find another solution. But this solution works quite well. If we need to move from it we should. What do you think?

**Comment by aspittel** [comment]
I think I'm okay with it looking a little off on IE since not too many programmers use it anyways! This looks great -- thanks @twhite96 and @twosmalltrees!

**Comment by twhite96** [comment]
Okay. Going to close this then.
