### ISSUE TITLE
Add balance to header

### ISSUE THREAD

**Issue by aspittel** [aspittel/learn-code-from-us#73]
I think the font for the logo is a little small right now -- I think it would look better if "Learn Code from Us" was a little bigger and the other text was a little smaller.

<img width="956" alt="screen shot 2018-10-30 at 11 53 45 am" src="https://user-images.githubusercontent.com/12969662/47731448-860ccd80-dc3a-11e8-8394-11e5516f0351.png">

**Comment by harleo** [comment]
I'll take a look.
Can you point to the file in question?

**Comment by pinkmadkitten** [comment]
I'll take care of this issue

**Comment by aspittel** [comment]
Thank you all so much! Got a bunch of PRs on this -- going to close out!
