### ISSUE TITLE
Getting in contact with the maintainers isn't obvious.

### ISSUE THREAD

**Issue by bhaibel** [aspittel/learn-code-from-us#89]
## Context
I'm a content creator who falls in line with the Learn Code from Us submission guidelines, but I'm a bit of a weird case. The details don't matter for this GitHub issue. Here's what does: 

1. I went to the submission form.
2. I had a hard time fitting my submission into the presented boxes.
3. I saw instructions to "contact us" if we didn't fit the existing form well.
4. But there wasn't a link to a contact form, or an email address, or anything like that.
5. OH NOES! USER CONFUSION!

I needed to click through to Ali's dev.to post, the one linked on the about page, and then skim that to find the GitHub repo. Honestly, I'm not sure I would have even known to do that if I hadn't gotten here from dev.to in the first place! I would have been stuck knowing I needed to contact y'all, but not knowing how to do so. That would mean a lost submission.

It would be really helpful if the UX around contacting the maintainers and/or getting started as a contributor could be made more obvious.

**Comment by aspittel** [comment]
Awesome feedback, thank you so much. Added contact information. Does [this](https://airtable.com/shrYbUMMlR1iVpA1l) look okay? Right now,  I'm the only person who interacts with the data, mainly because I've gotten a lot of trolling through the form, and I would rather take that on solo for now.

**Comment by bhaibel** [comment]
Yep! That looks great.

**Comment by aspittel** [comment]
Awesome thanks!
